'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const { createMockZernio } = require('../support/mock-zernio.cjs')
const { createPostingMock } = require('../support/mock-posts.cjs')
const { buildApp, launchApp, ROOT } = require('../support/electron-app.cjs')

const KEY = 'automation-e2e-key'
const FFMPEG = fs.existsSync(path.join(ROOT, 'engine-bin', 'ffmpeg')) ? path.join(ROOT, 'engine-bin', 'ffmpeg') : 'ffmpeg'

/** Picks an option from one of the app's dropdowns (a combobox button with a listbox menu). */
async function choose(page, combobox, name) {
  await combobox.click()
  await page.getByRole('listbox').getByRole('option', { name, exact: true }).click()
}

test('add library clips, review TikTok, and run a mixed-platform automation', { timeout: 180_000 }, async (t) => {
  const work = fs.mkdtempSync(path.join(os.tmpdir(), 'bridgeclip-automation-e2e-'))
  const clip = path.join(work, 'new_clip.mp4')
  execFileSync(FFMPEG, ['-v', 'error', '-y', '-f', 'lavfi', '-i', 'color=c=green:s=360x640:d=4:r=15',
    '-f', 'lavfi', '-i', 'sine=frequency=440:duration=4', '-shortest', '-c:v', 'mpeg4', '-q:v', '8',
    '-c:a', 'aac', '-movflags', '+faststart', clip])
  const run = path.join(work, 'userData', 'CreatorClips', 'automation-library-run')
  fs.mkdirSync(run, { recursive: true })
  const clips = ['first.mp4', 'second.mp4'].map((name) => {
    const target = path.join(run, name)
    fs.copyFileSync(clip, target)
    return target
  })
  fs.writeFileSync(path.join(run, 'job_output.json'), JSON.stringify({
    job_id: 'automation-library-run', source_video_title: 'Automation library run',
    source_video_description: 'A conversation about speech recognition for reliable automation.',
    clips: clips.map((file, index) => ({ clip_index: index, s3_url: `file://${file}`, duration_ms: 4000,
      start_time_ms: index * 4000, end_time_ms: (index + 1) * 4000, virality_score: 0.8 - index * 0.1,
      tags: index === 1 ? ['recognition'] : [], summary: index === 0 ? 'First library clip' : 'Second library clip' }))
  }))
  const posting = createPostingMock()
  let researchCalls = 0; let batchWritingCalls = 0; let failLargeBatches = false
  const enhancementInputs = []
  const mock = await createMockZernio({ apiKey: KEY, extraRoutes: [...posting.routes,
    { method: 'POST', path: '/speech', auth: false, handler: (ctx) => ctx.json(200, { text: 'Accurate transcripts make automations reliable.' }) },
    { method: 'POST', path: '/chat', auth: false, handler: (ctx) => {
      enhancementInputs.push(JSON.parse(ctx.body.messages[1].content))
      if (ctx.body.tools) { researchCalls++; return ctx.json(200, { choices: [{ message: { content: 'Relevant terms: speech recognition and reliable automation.', annotations: [{ type: 'url_citation', url_citation: { title: 'Recognition guide', url: 'https://example.com/recognition' } }] } }] }) }
      const input = JSON.parse(ctx.body.messages[1].content)
      if (failLargeBatches && input.clips?.length === 5) return ctx.json(503, { error: 'test provider interruption' })
      const posts = input.platforms.map(({ platform }) => ({ platform, title: platform === 'youtube' ? 'Why Transcript Accuracy Matters for Automation' : null, caption: 'Accurate transcripts make automations reliable. Here is the connection to speech recognition.', tags: platform === 'youtube' ? ['speech recognition'] : [], categoryId: platform === 'youtube' ? '28' : null, topicTag: null, evidence: 'Accurate transcripts make automations reliable.' }))
      if (input.clips) batchWritingCalls++
      ctx.json(200, { choices: [{ message: { content: JSON.stringify(input.clips ? { clips: input.clips.map((clip) => ({ id: clip.id, posts })) } : { posts }) } }] })
    } }
  ] })
  const [profile] = mock.state.profiles
  mock.addAccount('youtube', profile._id, { username: 'channel' })
  mock.addAccount('instagram', profile._id, { username: 'creator' })
  mock.addAccount('tiktok', profile._id, { username: 'tiktok-creator' })
  let session = null
  t.after(async () => {
    await session?.close()
    await mock.close()
    fs.rmSync(work, { recursive: true, force: true })
  })
  const appDir = buildApp(path.join(work, 'app'))
  session = await launchApp({ appDir, userDataDir: path.join(work, 'userData'), mock, env: { BRIDGECLIP_E2E_TRANSCRIPTION_URL: `${mock.url}/speech`, BRIDGECLIP_E2E_OPENROUTER_URL: `${mock.url}/chat`, PATH: `${process.env.PATH}${path.delimiter}${path.join(ROOT, 'engine-bin')}` } })
  const { page, app } = session
  page.setDefaultTimeout(15_000)
  await page.evaluate((key) => window.bridgeclip.settings.replaceApiKey('zernioApiKey', key), KEY)
  await page.evaluate(() => window.bridgeclip.settings.replaceApiKey('openrouterApiKey', 'e2e-only-key'))
  await page.reload()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByLabel('Automation name').fill('BridgeMind')
  await page.locator('form').getByRole('button', { name: 'Create' }).click()
  await page.getByRole('heading', { name: 'Content bank' }).waitFor()
  await page.getByRole('status', { name: 'Next posting slot' }).getByText('No times scheduled', { exact: true }).waitFor()

  await page.getByRole('button', { name: 'New profile' }).click()
  await page.getByLabel('New profile name').fill('Another profile')
  await page.locator('form').getByRole('button', { name: 'Create', exact: true }).click()
  await page.getByText('Profile “Another profile” created.').waitFor()
  await choose(page, page.getByLabel('Zernio profile'), profile.name)
  await page.getByRole('button', { name: 'Connect', exact: true }).click()
  await page.getByRole('heading', { name: 'Accounts', exact: true }).waitFor()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByRole('heading', { name: 'Content bank' }).waitFor()
  assert.equal(await page.getByLabel('Zernio profile').textContent(), profile.name)

  await page.getByRole('checkbox', { name: /@channel/ }).check()
  await page.getByRole('checkbox', { name: /@creator/ }).check()
  await page.getByRole('checkbox', { name: /@tiktok-creator/ }).check()
  const healthRequests = mock.state.requests.length
  const checkStatus = page.getByRole('button', { name: 'Check Zernio status', exact: true })
  await checkStatus.click()
  const statusCheck = page.getByRole('status', { name: 'Zernio status check' })
  await statusCheck.getByText('Upload hold: unconfirmed.', { exact: true }).waitFor()
  assert.equal(await statusCheck.getByText('Connection and permissions look good.', { exact: true }).count(), 3)
  assert.equal(posting.state.uploads.length, 0)
  assert.ok(mock.state.requests.slice(healthRequests).every((request) => request.method === 'GET'), 'checking status never creates a post or upload')
  const youtubeAccount = mock.state.accounts.find((account) => account.platform === 'youtube')
  mock.setHealth(youtubeAccount._id, { status: 'error', canPost: false, issues: ['Account temporarily rate-limited'] })
  await checkStatus.click()
  await statusCheck.getByText('Account temporarily rate-limited', { exact: true }).waitFor()
  mock.state.healthFails = true
  await checkStatus.click()
  await page.getByRole('alert').filter({ hasText: 'Status check failed:' }).waitFor()
  assert.equal(await statusCheck.count(), 0, 'a failed refresh removes the previous result')
  mock.state.healthFails = false
  mock.setHealth(youtubeAccount._id, { status: 'healthy', canPost: true, issues: [] })
  await checkStatus.click()
  await statusCheck.getByText('Upload hold: unconfirmed.', { exact: true }).waitFor()
  await page.getByRole('checkbox', { name: /@tiktok-creator/ }).uncheck()
  assert.equal(await statusCheck.count(), 0, 'changing target accounts clears the result')
  await page.getByRole('checkbox', { name: /@tiktok-creator/ }).check()
  assert.equal(await page.getByRole('switch', { name: 'Write captions with AI' }).isVisible(), false)
  await page.getByText('More settings', { exact: true }).click()
  assert.equal(await page.getByRole('switch', { name: 'Write captions with AI' }).getAttribute('aria-checked'), 'false')
  await page.getByRole('radiogroup', { name: 'YouTube visibility' }).getByRole('radio', { name: 'Unlisted' }).click()
  await page.locator('input[type="time"]').fill('23:59')
  await page.getByRole('button', { name: 'Add time' }).click()
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByText('Changes saved.').waitFor()
  await page.getByRole('switch', { name: 'Automation on' }).click()
  await page.getByText('BridgeMind is on.').waitFor()
  assert.match(await page.getByRole('region', { name: 'Queued', exact: true }).getByRole('status', { name: 'Next posting slot' }).textContent(), /Next slot (Today|Tomorrow) 11:59 PM · /)

  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Library/ }).click()
  await page.getByText('Automation library run').click()
  await page.getByRole('checkbox', { name: 'Select all clips' }).click()
  await page.getByRole('button', { name: 'Add 2 to automation' }).click()
  await page.getByRole('dialog', { name: 'Add to content bank' }).getByRole('button', { name: 'Add 2 clips' }).click()
  await page.getByRole('button', { name: 'View bank' }).click()
  await page.getByRole('heading', { name: 'Content bank' }).waitFor()
  // Real pointer dragging lifts the whole row and animates its neighbor.
  const queueRegion = page.getByRole('region', { name: 'Queued', exact: true })
  const queueOrder = () => queueRegion.locator('[data-rfd-draggable-id]').evaluateAll((rows) => rows.map((row) => row.querySelector('p').textContent))
  const firstHandle = page.getByRole('button', { name: 'Reorder First library clip', exact: true })
  const secondHandle = page.getByRole('button', { name: 'Reorder Second library clip', exact: true })
  await secondHandle.scrollIntoViewIfNeeded()
  const firstBox = await firstHandle.boundingBox()
  const secondBox = await secondHandle.boundingBox()
  await page.mouse.move(secondBox.x + secondBox.width / 2, secondBox.y + secondBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(secondBox.x + secondBox.width / 2, secondBox.y - 10, { steps: 3 })
  await page.locator('body > li[data-rfd-draggable-id]').waitFor()
  await page.mouse.move(firstBox.x + firstBox.width / 2, firstBox.y + firstBox.height / 2, { steps: 12 })
  await page.mouse.up()
  await page.waitForFunction(async () => (await window.bridgeclip.automations.list())[0].content[0].title === 'Second library clip')
  await page.locator('body > li[data-rfd-draggable-id]').waitFor({ state: 'detached' })
  assert.deepEqual(await queueOrder(), ['Second library clip', 'First library clip'])
  // Keyboard cancel preserves the saved order; Space commits a later move.
  await secondHandle.focus()
  await page.keyboard.press('Space')
  await page.locator('body > li[data-rfd-draggable-id]').waitFor()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Escape')
  await page.locator('body > li[data-rfd-draggable-id]').waitFor({ state: 'detached' })
  assert.deepEqual(await queueOrder(), ['Second library clip', 'First library clip'])
  await secondHandle.focus()
  await page.keyboard.press('Space')
  await page.locator('body > li[data-rfd-draggable-id]').waitFor()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Space')
  await page.waitForFunction(async () => (await window.bridgeclip.automations.list())[0].content[0].title === 'First library clip')
  await page.locator('body > li[data-rfd-draggable-id]').waitFor({ state: 'detached' })
  assert.deepEqual(await queueOrder(), ['First library clip', 'Second library clip'])
  const clipTitle = page.getByText('First library clip', { exact: true })
  await firstHandle.and(page.locator('[aria-disabled="false"]')).waitFor()
  await clipTitle.scrollIntoViewIfNeeded()
  await app.evaluate(({ clipboard }) => clipboard.writeText('before-copy'))
  const titleBounds = await clipTitle.boundingBox()
  assert.ok(titleBounds)
  await page.mouse.move(titleBounds.x + 2, titleBounds.y + titleBounds.height / 2)
  await page.mouse.down()
  await page.mouse.move(titleBounds.x + 85, titleBounds.y + titleBounds.height / 2, { steps: 10 })
  await page.mouse.up()
  const selection = await page.evaluate(() => window.getSelection()?.toString() ?? '')
  const selectionStyles = await clipTitle.evaluate((element) => ({
    text: getComputedStyle(element).userSelect,
    parent: getComputedStyle(element.parentElement).userSelect,
    scroll: getComputedStyle(document.getElementById('page-scroll')).userSelect
  }))
  assert.ok(selection.trim(), `content text can be selected (${JSON.stringify(selectionStyles)})`)
  await page.keyboard.press(process.platform === 'darwin' ? 'Meta+C' : 'Control+C')
  assert.equal(await app.evaluate(({ clipboard }) => clipboard.readText()), selection, 'the selected content copies to the clipboard')
  assert.equal(await page.getByRole('button', { name: 'Run now' }).isDisabled(), true)
  await page.getByRole('heading', { name: 'Queued 2', exact: true }).waitFor()
  await page.getByRole('heading', { name: 'Submitted 0', exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Review TikTok', exact: true }).count(), 2)
  const info = page.getByLabel('Info about First library clip', { exact: true })
  await info.hover()
  await page.getByRole('tooltip').getByText('Added to queue', { exact: true }).waitFor()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Actions for First library clip', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Edit', exact: true }).click()
  await page.getByRole('textbox', { name: 'Title', exact: true }).waitFor()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  // Exercise the real IPC boundary without opening the developer's Finder.
  await app.evaluate(({ shell }) => {
    globalThis.revealedBankFiles = []
    shell.showItemInFolder = (file) => { globalThis.revealedBankFiles.push(file) }
  })
  const revealLabel = process.platform === 'darwin' ? 'Show in Finder' : 'Show in folder'
  await page.getByRole('button', { name: 'Actions for First library clip', exact: true }).click()
  await page.getByRole('menuitem', { name: revealLabel, exact: true }).click()
  const revealed = await app.evaluate(async () => {
    for (let attempt = 0; attempt < 50 && !globalThis.revealedBankFiles.length; attempt++) await new Promise((resolve) => setTimeout(resolve, 20))
    return globalThis.revealedBankFiles
  })
  assert.equal(revealed.length, 1)
  const bankFile = revealed[0]
  assert.ok(bankFile.startsWith(path.join(work, 'userData', 'automation-bank') + path.sep), 'reveals the saved bank copy')
  assert.deepEqual(fs.readFileSync(bankFile), fs.readFileSync(clips[0]))
  const bankIds = await page.evaluate(async () => {
    const [automation] = await window.bridgeclip.automations.list()
    return { id: automation.id, contentId: automation.content.find((item) => item.title === 'First library clip').id }
  })
  await assert.rejects(page.evaluate(({ id }) => window.bridgeclip.automations.showInFolder(id, '../unrecorded.mp4'), bankIds), /Clip not found/)
  fs.renameSync(bankFile, `${bankFile}.saved`)
  try {
    await page.getByRole('button', { name: 'Actions for First library clip', exact: true }).click()
    await page.getByRole('menuitem', { name: revealLabel, exact: true }).click()
    await page.getByText('This clip’s video file is no longer available.', { exact: true }).waitFor()
    fs.symlinkSync(clips[0], bankFile)
    assert.equal(await page.evaluate(({ id, contentId }) => window.bridgeclip.automations.showInFolder(id, contentId), bankIds), false, 'does not reveal a substituted symlink')
    assert.equal(await app.evaluate(() => globalThis.revealedBankFiles.length), 1)
  } finally {
    fs.rmSync(bankFile, { force: true })
    fs.renameSync(`${bankFile}.saved`, bankFile)
  }
  await page.getByRole('button', { name: 'View First library clip in Library', exact: true }).click()
  await page.getByRole('heading', { name: 'Automation library run', exact: true }).waitFor()
  await page.getByText('From content bank · Clip 1', { exact: true }).waitFor()
  assert.equal(await page.locator('article').count(), 1)
  await page.getByText('First library clip', { exact: true }).waitFor()
  assert.equal(await page.getByText('Second library clip', { exact: true }).count(), 0)
  await page.getByRole('button', { name: 'Show all clips', exact: true }).click()
  assert.equal(await page.locator('article').count(), 2)
  const searchClips = page.getByRole('textbox', { name: 'Search clips', exact: true })
  await searchClips.fill('  RECOGNITION  ')
  assert.equal(await page.locator('article').count(), 1)
  await page.getByText('Second library clip', { exact: true }).waitFor()
  await page.getByRole('checkbox', { name: 'Select all clips' }).check()
  await page.getByRole('button', { name: 'Add 1 to automation', exact: true }).waitFor()
  await searchClips.fill('Clip 1')
  await page.getByText('First library clip', { exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Add 1 to automation', exact: true }).count(), 0)
  await searchClips.fill('no such clip')
  await page.getByText('No clips match your search', { exact: true }).waitFor()
  assert.equal(await page.locator('article').count(), 0)
  await page.getByRole('button', { name: 'Show all clips', exact: true }).click()
  await searchClips.fill('SECOND LIBRARY')
  assert.equal(await page.locator('article').count(), 1)
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Library/ }).click()
  await page.getByText('Automation library run').click()
  assert.equal(await searchClips.inputValue(), '')
  assert.equal(await page.locator('article').count(), 2)
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByRole('button', { name: 'Review TikTok', exact: true }).first().click()
  const review = page.getByRole('dialog', { name: 'Review for TikTok' })
  const audience = review.getByLabel('Who can view this video')
  await audience.waitFor()
  assert.equal(await audience.textContent(), 'Choose who can view', 'privacy has no default')
  assert.equal(await review.getByRole('button', { name: 'Approve for automation' }).isDisabled(), true)
  assert.equal(posting.state.uploads.length, 0)
  await review.getByLabel('TikTok caption').fill('Reviewed TikTok caption #Clips')
  await choose(page, audience, 'Everyone')
  const consent = review.getByRole('checkbox', { name: /By posting, you agree/ })
  const previewConsent = review.getByRole('checkbox', { name: 'I reviewed this clip and caption for TikTok' })
  await consent.check()
  await review.getByRole('switch', { name: 'Send to your TikTok inbox', exact: true }).click()
  assert.equal(await consent.isChecked(), false, 'changing delivery mode requires consent again')
  await review.getByRole('switch', { name: 'Send to your TikTok inbox', exact: true }).click()
  await previewConsent.check()
  await review.getByLabel('TikTok caption').fill('Edited again before approval')
  assert.equal(await previewConsent.isChecked(), false, 'changing the caption requires reviewing it again')
  await review.getByLabel('TikTok caption').fill('Reviewed TikTok caption #Clips')
  await consent.check()
  await previewConsent.check()
  await review.getByRole('button', { name: 'Approve for automation' }).click()
  await page.getByText('TikTok review saved.').waitFor()
  assert.equal(posting.state.uploads.length, 0)
  await page.getByRole('button', { name: 'Actions for First library clip', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Edit TikTok', exact: true }).click()
  await audience.waitFor()
  assert.equal(await review.getByLabel('TikTok caption').inputValue(), 'Reviewed TikTok caption #Clips')
  assert.equal(await audience.textContent(), 'Choose who can view', 'reopened reviews require a fresh audience choice')
  await review.getByRole('button', { name: 'Cancel', exact: true }).click()
  const firstClipRow = page.locator('li').filter({ has: page.getByText('First library clip', { exact: true }) })
  await firstClipRow.getByRole('button', { name: 'Review TikTok', exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Run now' }).isDisabled(), true, 'cancelled edits leave the clip awaiting approval')
  await firstClipRow.getByRole('button', { name: 'Review TikTok', exact: true }).click()
  await audience.waitFor()
  assert.equal(await review.getByLabel('TikTok caption').inputValue(), 'Reviewed TikTok caption #Clips', 'cancelling preserves the last reviewed caption')
  await choose(page, audience, 'Everyone')
  await review.getByRole('checkbox', { name: /By posting, you agree/ }).check()
  await review.getByRole('checkbox', { name: 'I reviewed this clip and caption for TikTok' }).check()
  await review.getByRole('button', { name: 'Approve for automation' }).click()
  await review.waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: 'Run now' }).click()
  await page.getByText('Run finished. Check the content bank for the result.').waitFor()

  assert.equal(posting.state.uploads.length, 1)
  assert.equal(posting.state.creates.length, 1)
  assert.deepEqual(posting.state.creates[0].body.platforms.map((target) => target.platform), ['youtube', 'instagram', 'tiktok'])
  assert.equal(posting.state.creates[0].body.platforms[0].platformSpecificData.visibility, 'unlisted')
  assert.equal(posting.state.creates[0].body.platforms[2].customContent, 'Reviewed TikTok caption #Clips')
  assert.equal(await page.getByRole('button', { name: 'Run now' }).isDisabled(), true, 'the remaining clip requires its own TikTok review')
  await page.getByRole('checkbox', { name: /@tiktok-creator/ }).uncheck()
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByText('Changes saved.').waitFor()
  await page.getByRole('button', { name: 'Enhance', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Enhance title & caption' })
  await dialog.getByRole('button', { name: 'Generate draft' }).waitFor()
  await page.waitForFunction(() => document.querySelector('input[id$="-source-title"]')?.value === 'Automation library run')
  assert.equal(await dialog.getByLabel('Original description', { exact: true }).inputValue(), 'A conversation about speech recognition for reliable automation.')
  await dialog.getByRole('button', { name: 'Generate draft' }).click()
  dialog = page.getByRole('dialog', { name: 'Review enhanced metadata' })
  await dialog.getByText('Why Transcript Accuracy Matters for Automation', { exact: true }).waitFor()
  assert.equal(posting.state.creates.length, 1, 'enhancing never publishes')
  await dialog.getByText('Context & research · complete').click()
  await dialog.getByText('Recognition guide', { exact: false }).waitFor()
  if (process.env.BRIDGECLIP_ENHANCEMENT_SCREENSHOT) await page.screenshot({ path: process.env.BRIDGECLIP_ENHANCEMENT_SCREENSHOT })
  await dialog.getByRole('button', { name: 'Review later' }).click()
  assert.equal(await page.getByRole('button', { name: 'Run now' }).isDisabled(), true, 'a pending draft holds its clip')
  assert.equal(posting.state.creates.length, 1, 'pending draft holds its clip')
  await page.getByRole('button', { name: 'Review draft' }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Apply metadata' }).click()
  await page.getByText('Why Transcript Accuracy Matters for Automation', { exact: true }).waitFor()
  const saved = await page.evaluate(() => window.bridgeclip.automations.list())
  assert.equal(saved[0].content[1].metadataDraft, null)
  assert.equal(saved[0].content[1].generatedMetadata[0].title, 'Why Transcript Accuracy Matters for Automation')
  assert.equal(posting.state.creates.length, 1, 'applying copy does not publish immediately')
  // Enhanced titles still link to the exact original clip, not a title search.
  await page.getByRole('button', { name: 'View Why Transcript Accuracy Matters for Automation in Library', exact: true }).click()
  await page.getByText('From content bank · Clip 2', { exact: true }).waitFor()
  assert.equal(await page.locator('article').count(), 1)
  await page.getByText('Second library clip', { exact: true }).waitFor()
  if (process.env.BRIDGECLIP_LIBRARY_FILTER_SCREENSHOT) await page.screenshot({ path: process.env.BRIDGECLIP_LIBRARY_FILTER_SCREENSHOT })
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  // A submitted clip is visible even though Posted normally starts collapsed.
  await page.getByRole('button', { name: 'View First library clip in Library', exact: true }).click()
  await page.getByText('From content bank · Clip 1', { exact: true }).waitFor()
  await page.getByText('First library clip', { exact: true }).waitFor()
  assert.equal(await page.locator('article').count(), 1)
  await page.evaluate(async ({ run }) => {
    const [automation] = await window.bridgeclip.automations.list()
    await window.bridgeclip.automations.addLibraryClips(automation.id, run, [0, 1])
  }, { run })
  await page.reload()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByRole('button', { name: 'Enhance by source video' }).click()
  await page.getByLabel('Original video', { exact: true }).waitFor()
  assert.match(await page.getByLabel('Original video', { exact: true }).textContent(), /Automation library run · 2 clips/)
  if (process.env.BRIDGECLIP_BATCH_SCREENSHOT) await page.screenshot({ path: process.env.BRIDGECLIP_BATCH_SCREENSHOT })
  await page.getByRole('button', { name: 'Enhance 2 clips from this video' }).click()
  await page.getByText(/2 drafts ready to review/).waitFor()
  assert.equal(batchWritingCalls, 1, 'one writing request for two clips')
  assert.equal(researchCalls, 1, 'batch reuses the source research from individual enhancement')
  assert.equal(posting.state.creates.length, 1, 'batch does not publish')
  assert.equal(await page.getByRole('button', { name: 'Review draft', exact: true }).count(), 2)
  // A failed five-clip request must not prevent the later batch from running.
  await page.evaluate(async ({ run }) => {
    const [automation] = await window.bridgeclip.automations.list()
    for (let batch = 0; batch < 3; batch++) await window.bridgeclip.automations.addLibraryClips(automation.id, run, [0, 1])
  }, { run })
  failLargeBatches = true
  await page.reload()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByRole('button', { name: 'Enhance by source video' }).click()
  await page.getByText('Attached file ·', { exact: false }).waitFor()
  const guidance = 'A workshop on speech recognition. Focus on practical automation tips for beginners.'
  await page.getByLabel('Enhancement prompt (optional)').fill(guidance)
  if (process.env.BRIDGECLIP_GUIDANCE_SCREENSHOT) await page.screenshot({ path: process.env.BRIDGECLIP_GUIDANCE_SCREENSHOT })
  const requestsBeforeGuidance = enhancementInputs.length
  await page.getByRole('button', { name: 'Enhance 6 clips from this video' }).click()
  await page.getByText(/1 drafts ready to review · 5 failed · 0 already handled · 0 not attempted/).waitFor()
  const afterFailure = await page.evaluate(() => window.bridgeclip.automations.list())
  assert.equal(afterFailure[0].content.filter((item) => item.metadataError).length, 5)
  assert.equal(afterFailure[0].content.at(-1).metadataDraft.posts.length, 2)
  assert.equal(afterFailure[0].content.at(-1).metadataDraft.guidance, guidance)
  assert.ok(enhancementInputs.slice(requestsBeforeGuidance).every((input) => input.enhancementGuidance === guidance), 'prompt is forwarded through IPC to research and every writing chunk')
  assert.equal(researchCalls, 2, 'new guidance refreshes research once for both chunks')
  assert.equal(posting.state.creates.length, 1)
  await page.reload()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByText(/Metadata enhancement failed:/).first().waitFor()
  const failedAlerts = page.getByRole('status').filter({ hasText: /^Metadata enhancement failed:/ })
  assert.equal(await failedAlerts.count(), 5)
  await failedAlerts.first().getByRole('button', { name: 'Dismiss', exact: true }).click()
  await page.waitForFunction(async () => (await window.bridgeclip.automations.list())[0].content.filter((item) => item.metadataErrorAcknowledged).length === 1)
  assert.equal(await failedAlerts.count(), 4, 'dismiss affects only the chosen clip')
  await page.reload()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await failedAlerts.first().waitFor()
  assert.equal(await failedAlerts.count(), 4, 'per-clip dismissal survives reload')
  await failedAlerts.first().scrollIntoViewIfNeeded()
  if (process.env.BRIDGECLIP_CONTENT_BANK_SCREENSHOT) await page.screenshot({ path: process.env.BRIDGECLIP_CONTENT_BANK_SCREENSHOT })
  // Tall warnings stay attached to the pointer and the page scrolls at its edge.
  const savedOrder = await queueRegion.locator('[data-rfd-draggable-id]').evaluateAll((rows) => rows.map((row) => row.dataset.rfdDraggableId))
  const tallRow = queueRegion.locator('li').filter({ has: page.getByRole('status').filter({ hasText: /^Metadata enhancement failed:/ }) }).first()
  const tallHandle = tallRow.getByRole('button', { name: /^Reorder / })
  await tallHandle.scrollIntoViewIfNeeded()
  const tallBox = await tallHandle.boundingBox()
  const scrollBefore = await page.locator('#page-scroll').evaluate((element) => element.scrollTop)
  const scrollBox = await page.locator('#page-scroll').boundingBox()
  await page.mouse.move(tallBox.x + tallBox.width / 2, tallBox.y + tallBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(tallBox.x + tallBox.width / 2, tallBox.y + tallBox.height / 2 + 12, { steps: 3 })
  await page.locator('body > li[data-rfd-draggable-id]').waitFor()
  if (process.env.BRIDGECLIP_CONTENT_BANK_SCREENSHOT) await page.screenshot({ path: `${process.env.BRIDGECLIP_CONTENT_BANK_SCREENSHOT}.drag.png` })
  await page.mouse.move(tallBox.x + tallBox.width / 2, scrollBox.y + scrollBox.height - 15, { steps: 15 })
  await page.waitForFunction((before) => document.querySelector('#page-scroll').scrollTop > before + 30, scrollBefore, { timeout: 10_000 })
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await page.locator('body > li[data-rfd-draggable-id]').waitFor({ state: 'detached' })
  assert.deepEqual(await queueRegion.locator('[data-rfd-draggable-id]').evaluateAll((rows) => rows.map((row) => row.dataset.rfdDraggableId)), savedOrder)

  await page.getByRole('button', { name: 'Acknowledge all warnings', exact: true }).click()
  await page.getByText('Warnings acknowledged across all automations. Held clips remain held.', { exact: true }).waitFor()
  assert.equal(await page.getByText(/Metadata enhancement failed:/).count(), 0)
  assert.equal(await page.getByRole('button', { name: 'Acknowledge all warnings', exact: true }).count(), 0)
  assert.equal(posting.state.creates.length, 1, 'acknowledging never posts a clip')
  await page.reload()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByRole('heading', { name: 'Content bank', exact: true }).waitFor()
  assert.equal(await page.getByText(/Metadata enhancement failed:/).count(), 0, 'acknowledgement survives a reload')
  await page.getByRole('button', { name: 'Review draft', exact: true }).last().click()
  const guidedReview = page.getByRole('dialog', { name: 'Review enhanced metadata' })
  await guidedReview.getByText('Context & research · complete', { exact: false }).click()
  await guidedReview.getByText(guidance, { exact: false }).waitFor()
  await guidedReview.getByRole('button', { name: 'Review later' }).click()
  // Switching between an attached source and a linked one keeps their prompts separate.
  const linkedRun = path.join(path.dirname(run), 'linked-source-run')
  fs.mkdirSync(linkedRun)
  const linkedClip = path.join(linkedRun, 'linked.mp4'); fs.copyFileSync(clip, linkedClip)
  fs.writeFileSync(path.join(linkedRun, 'job_output.json'), JSON.stringify({
    job_id: 'linked-source-run', source_video_title: 'Linked source video',
    source_video_url: 'https://www.youtube.com/watch?v=hqP9fivmBqI', source_video_description: 'Speech recognition tips.',
    clips: [{ clip_index: 0, s3_url: `file://${linkedClip}`, duration_ms: 4000, start_time_ms: 0, end_time_ms: 4000, summary: 'Linked clip', virality_score: 0.8 }]
  }))
  await page.evaluate(async (run) => {
    const [automation] = await window.bridgeclip.automations.list()
    await window.bridgeclip.automations.addLibraryClips(automation.id, run, [0])
  }, linkedRun)
  await page.getByRole('button', { name: 'Enhance by source video' }).click()
  await page.getByLabel('Enhancement prompt (optional)').fill('Attached source notes')
  await choose(page, page.getByLabel('Original video', { exact: true }), 'Linked source video · 1 clip')
  await page.getByText('Linked video ·', { exact: false }).waitFor()
  assert.equal(await page.getByLabel('Enhancement prompt (optional)').inputValue(), '')
  const linkedGuidance = 'Focus on speech recognition for a technical audience.'
  await page.getByLabel('Enhancement prompt (optional)').fill(linkedGuidance)
  await choose(page, page.getByLabel('Original video', { exact: true }), 'Automation library run · 5 clips')
  assert.equal(await page.getByLabel('Enhancement prompt (optional)').inputValue(), 'Attached source notes')
  await choose(page, page.getByLabel('Original video', { exact: true }), 'Linked source video · 1 clip')
  assert.equal(await page.getByLabel('Enhancement prompt (optional)').inputValue(), linkedGuidance)
  await page.getByRole('button', { name: 'Enhance 1 clip from this video' }).click()
  await page.getByText(/1 drafts ready to review · 0 failed/).waitFor()
  assert.equal(enhancementInputs.at(-1).enhancementGuidance, linkedGuidance)
  assert.equal(enhancementInputs.at(-1).sourceContext.url, 'https://www.youtube.com/watch?v=hqP9fivmBqI')
  assert.equal(posting.state.creates.length, 1)
  // The per-automation action clears the header flag while retaining its message.
  await page.evaluate(async () => {
    const [automation] = await window.bridgeclip.automations.create('Warning history')
    await window.bridgeclip.automations.run(automation.id) // Empty bank: no upload or post.
  })
  await page.reload()
  await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await page.getByRole('navigation', { name: 'Automations', exact: true }).getByRole('button', { name: 'Warning history', exact: true }).click()
  await page.getByText('Last run failed · View details', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Acknowledge warnings', exact: true }).click()
  await page.getByText('Previous run issue · Acknowledged', { exact: true }).click()
  await page.getByText('No queued clips are available.', { exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Acknowledge warnings', exact: true }).count(), 0)
  assert.equal(posting.state.creates.length, 1)

  // Reproduce a stale held post that later published, alongside an unlinked held clip.
  await session.close(); session = null
  const userData = path.join(work, 'userData')
  const bankPath = path.join(userData, fs.readdirSync(userData).find((name) => /^automations-.*\.json$/.test(name)))
  const banks = JSON.parse(fs.readFileSync(bankPath, 'utf8'))
  const recoveryBank = banks.automations.find((item) => item.name === 'BridgeMind')
  recoveryBank.enabled = false
  const [publishedClip, unlinkedClip] = recoveryBank.content
  assert.ok(publishedClip.postId)
  Object.assign(publishedClip, { status: 'needs_review', error: 'All platforms failed', warningsAcknowledged: true })
  Object.assign(unlinkedClip, { status: 'needs_review', postId: null, error: 'Rate limited', warningsAcknowledged: true })
  fs.writeFileSync(bankPath, JSON.stringify(banks))
  session = await launchApp({ appDir, userDataDir: userData, mock })
  const recoveryPage = session.page
  await recoveryPage.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
  await recoveryPage.getByRole('navigation', { name: 'Automations', exact: true }).getByRole('button', { name: 'BridgeMind', exact: true }).click()
  const held = recoveryPage.getByRole('region', { name: 'Held clips', exact: true })
  // Removing local post history must not strand its held automation clip.
  await recoveryPage.evaluate((id) => window.bridgeclip.zernio.posts.dismiss(id), publishedClip.postId)
  await held.getByRole('button', { name: 'Refresh post status', exact: true }).click()
  await recoveryPage.getByText('Zernio already has this post published or in progress. The clip was moved to Submitted.', { exact: true }).waitFor()
  assert.equal(await held.getByRole('button', { name: 'Return to queue', exact: true }).count(), 1)
  await held.getByRole('button', { name: 'Return to queue', exact: true }).click()
  const returnDialog = recoveryPage.getByRole('alertdialog', { name: 'Return this clip to the queue?' })
  await returnDialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  assert.equal(await held.getByRole('button', { name: 'Return to queue', exact: true }).count(), 1)
  await held.getByRole('button', { name: 'Return to queue', exact: true }).click()
  await returnDialog.getByRole('button', { name: 'Return to queue', exact: true }).click()
  await recoveryPage.getByText('Clip returned to the queue.', { exact: true }).waitFor()
  assert.equal(await held.count(), 0)
  const recoveredBank = await recoveryPage.evaluate(async (id) => (await window.bridgeclip.automations.list()).find((item) => item.id === id), recoveryBank.id)
  assert.equal(recoveredBank.content[0].status, 'posted')
  assert.equal(recoveredBank.content[1].status, 'queued')
  assert.equal(posting.state.creates.length, 1, 'recovering held clips never submits another post')
})

test('dismiss an upload error and retry that exact clip after Run now skips it', { timeout: 120_000 }, async (t) => {
  const work = fs.mkdtempSync(path.join(os.tmpdir(), 'bridgeclip-upload-recovery-e2e-'))
  const posting = createPostingMock()
  const mock = await createMockZernio({ apiKey: KEY, extraRoutes: posting.routes })
  const profile = mock.state.profiles[0]
  const youtube = mock.addAccount('youtube', profile._id)
  let session
  t.after(async () => {
    await session?.close()
    await mock.close()
    fs.rmSync(work, { recursive: true, force: true })
  })
  const appDir = buildApp(path.join(work, 'app'))
  session = await launchApp({ appDir, userDataDir: path.join(work, 'userData'), mock })
  const { page } = session
  page.setDefaultTimeout(15_000)
  await page.evaluate((key) => window.bridgeclip.settings.replaceApiKey('zernioApiKey', key), KEY)
  const output = await page.evaluate(async () => (await window.bridgeclip.settings.load()).outputDirectory)
  const run = path.join(output, 'upload-recovery'); fs.mkdirSync(run, { recursive: true })
  const titles = ['Failed clip', 'Fresh clip', 'Later clip']
  const files = ['blue', 'red', 'green'].map((color, index) => {
    const file = path.join(run, `${index}.mp4`)
    execFileSync(FFMPEG, ['-v', 'error', '-y', '-f', 'lavfi', '-i', `color=c=${color}:s=360x640:d=2:r=15`,
      '-f', 'lavfi', '-i', 'sine=frequency=440:duration=2', '-shortest', '-c:v', 'mpeg4', '-c:a', 'aac', file])
    return file
  })
  fs.writeFileSync(path.join(run, 'job_output.json'), JSON.stringify({ job_id: 'upload-recovery', source_video_title: 'Recovery video',
    clips: files.map((file, index) => ({ clip_index: index, s3_url: `file://${file}`, duration_ms: 2000,
      start_time_ms: index * 2000, end_time_ms: (index + 1) * 2000, summary: titles[index], virality_score: .8 })) }))
  const id = await page.evaluate(async ({ profileId, accountId, run }) => {
    const [bank] = await window.bridgeclip.automations.create('Upload recovery')
    await window.bridgeclip.automations.update(bank.id, { name: bank.name, enabled: false, profileId, accounts: [{ platform: 'youtube', accountId }],
      metadataMode: 'manual', times: [], timezone: 'UTC', youtubeVisibility: 'unlisted', youtubeMadeForKids: false })
    await window.bridgeclip.automations.addLibraryClips(bank.id, run, [0, 1, 2])
    return bank.id
  }, { profileId: profile._id, accountId: youtube._id, run })
  const openBank = async () => {
    await page.reload()
    await page.getByRole('navigation', { name: 'Main' }).getByRole('button', { name: /Automations/ }).click()
    await page.getByRole('heading', { name: 'Content bank', exact: true }).waitFor()
  }
  await openBank()
  const failedRow = page.locator('[data-rfd-draggable-id]').filter({ has: page.getByText('Failed clip', { exact: true }) })
  posting.state.failNextUpload = 503
  await page.getByRole('button', { name: 'Run now', exact: true }).click()
  await failedRow.getByRole('alert').waitFor()
  await failedRow.getByRole('button', { name: 'Retry clip', exact: true }).waitFor()
  await page.getByRole('button', { name: 'Run now', exact: true }).click()
  await page.getByRole('region', { name: 'Submitted', exact: true }).getByText('Fresh clip', { exact: true }).waitFor()
  assert.equal(posting.state.creates.length, 1)
  await failedRow.getByRole('alert').getByRole('button', { name: 'Dismiss', exact: true }).click()
  await failedRow.getByRole('alert').waitFor({ state: 'detached' })
  await openBank()
  await failedRow.getByRole('button', { name: 'Retry clip', exact: true }).waitFor()
  assert.equal(await failedRow.getByRole('alert').count(), 0, 'dismissal survives reload')
  const bankBeforeRetry = await page.evaluate(async (id) => (await window.bridgeclip.automations.list()).find((bank) => bank.id === id), id)
  assert.equal(bankBeforeRetry.content[0].status, 'queued')
  assert.ok(bankBeforeRetry.content[0].error, 'dismissal keeps error history')
  assert.equal(posting.state.creates.length, 1, 'dismissal never publishes')
  posting.state.failNextUpload = 503
  await failedRow.getByRole('button', { name: 'Retry clip', exact: true }).click()
  await failedRow.getByRole('alert').waitFor()
  assert.equal(posting.state.creates.length, 1, 'a failed retry never falls through to another clip')
  if (process.env.BRIDGECLIP_UPLOAD_RECOVERY_SCREENSHOT) await page.screenshot({ path: process.env.BRIDGECLIP_UPLOAD_RECOVERY_SCREENSHOT })
  await failedRow.getByRole('button', { name: 'Retry clip', exact: true }).click()
  await page.getByRole('region', { name: 'Submitted', exact: true }).getByText('Failed clip', { exact: true }).waitFor()
  await page.getByRole('region', { name: 'Queued', exact: true }).getByText('Later clip', { exact: true }).waitFor()
  assert.equal(posting.state.creates.length, 2)
  assert.equal(await failedRow.getByRole('button', { name: 'Retry clip', exact: true }).count(), 0)
})
