const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { execFileSync } = require('node:child_process')
const { buildApp, launchApp, ROOT } = require('../zernio/support/electron-app.cjs')

test('Library deletes only selected clips through its icon action and refreshes counts and empty state', { timeout: 90000 }, async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bridgeclip-delete-clips-'))
  const userDataDir = path.join(root, 'user-data'), library = path.join(userDataDir, 'CreatorClips'), run = path.join(library, 'test-run')
  fs.mkdirSync(run, { recursive: true })
  const ffmpeg = fs.existsSync(path.join(ROOT, 'engine-bin/ffmpeg')) ? path.join(ROOT, 'engine-bin/ffmpeg') : 'ffmpeg'
  execFileSync(ffmpeg, ['-v', 'error', '-f', 'lavfi', '-i', 'testsrc2=size=320x180:rate=10', '-t', '1', '-c:v', 'mpeg4', path.join(run, 'clip_00.mp4')])
  const clips = ['First clip', 'Second clip', 'Third clip', 'Fourth clip'].map((summary, clip_index) => {
    const file = path.join(run, `clip_0${clip_index}.mp4`)
    if (clip_index) fs.copyFileSync(path.join(run, 'clip_00.mp4'), file)
    return { clip_index, summary, s3_url: file, start_time_ms: 0, end_time_ms: 1000, duration_ms: 1000, virality_score: 90 - clip_index }
  })
  const output = { job_id: 'test-run', source_video_title: 'Delete selected test', source_video_url: 'local.mp4', source_video_duration_seconds: 1, clips, total_clips: 4 }
  const manifest = path.join(run, 'job_output.json')
  fs.writeFileSync(manifest, JSON.stringify(output))
  fs.writeFileSync(path.join(run, 'transcript.json'), '{"segments":[]}')
  fs.copyFileSync(clips[0].s3_url, path.join(run, 'framing-source.mp4'))
  const session = await launchApp({ appDir: buildApp(path.join(root, 'app')), userDataDir })
  t.after(async () => { await session.close(); fs.rmSync(root, { recursive: true, force: true }) })
  const { app, page } = session
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  page.setDefaultTimeout(10000)
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1400, 900))
  await page.getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('button', { name: 'Open Delete selected test', exact: true }).click()
  // Manual posting works without a connected account and survives reopening the run.
  const clipActions = page.getByRole('button', { name: 'Actions for “First clip”', exact: true })
  await clipActions.click()
  assert.deepEqual(await page.getByRole('menuitem').allTextContents(), ['Post or schedule', 'Add to automation', 'Mark as posted', process.platform === 'darwin' ? 'Show in Finder' : 'Show in folder', 'Delete clip'])
  await page.getByRole('menuitem', { name: 'Mark as posted', exact: true }).click()
  await page.getByRole('region', { name: 'Posted 1', exact: true }).getByText('First clip', { exact: true }).waitFor()
  assert.ok(fs.existsSync(path.join(run, '.bridgeclip-posted-0')))
  assert.equal(fs.readFileSync(manifest, 'utf8'), JSON.stringify(output))
  await page.getByRole('button', { name: 'Library', exact: true }).first().click()
  await page.getByRole('button', { name: 'Open Delete selected test', exact: true }).click()
  await page.getByRole('button', { name: 'Posted 1', exact: true }).click()
  await clipActions.click()
  await page.getByRole('menuitem', { name: 'Undo manual posted mark', exact: true }).click()
  await page.getByRole('region', { name: 'Not Posted 4', exact: true }).getByText('First clip', { exact: true }).waitFor()
  assert.equal(fs.existsSync(path.join(run, '.bridgeclip-posted-0')), false)
  // Failed writes leave the card unposted and expose a retryable error.
  fs.renameSync(manifest, `${manifest}.backup`)
  await clipActions.click()
  await page.getByRole('menuitem', { name: 'Mark as posted', exact: true }).click()
  await page.getByRole('alert').getByText(/This completed run is no longer available/).waitFor()
  assert.equal(fs.existsSync(path.join(run, '.bridgeclip-posted-0')), false)
  fs.renameSync(`${manifest}.backup`, manifest)
  // An individual clip can be deleted without first selecting any cards.
  const fourthActions = page.getByRole('button', { name: 'Actions for “Fourth clip”', exact: true })
  await fourthActions.click()
  await page.getByRole('menuitem', { name: 'Delete clip', exact: true }).press('Enter')
  const singleConfirmation = page.getByRole('alertdialog', { name: 'Delete this clip?', exact: true })
  await singleConfirmation.getByText(/“Fourth clip” and its local video file/).waitFor()
  await singleConfirmation.getByRole('button', { name: 'Cancel', exact: true }).click()
  assert.ok(clips.every(clip => fs.existsSync(clip.s3_url)))
  assert.equal(JSON.parse(fs.readFileSync(manifest)).clips.length, 4)
  await fourthActions.click()
  await page.getByRole('menuitem', { name: 'Delete clip', exact: true }).click()
  await singleConfirmation.getByRole('button', { name: 'Delete clip', exact: true }).click()
  await fourthActions.waitFor({ state: 'detached' })
  await page.getByRole('button', { name: 'Not Posted 3', exact: true }).waitFor()
  assert.equal(fs.existsSync(clips[3].s3_url), false)
  assert.ok(clips.slice(0, 3).every(clip => fs.existsSync(clip.s3_url)))
  assert.deepEqual(JSON.parse(fs.readFileSync(manifest)).clips.map(c => c.clip_index), [0, 1, 2])
  const trash = page.getByRole('button', { name: 'Delete selected clips', exact: true })
  assert.equal(await trash.count(), 0)
  await page.getByRole('checkbox', { name: 'Select First clip', exact: true }).click()
  await trash.waitFor()
  assert.equal(await trash.innerText(), '')
  assert.equal(await trash.locator('svg.lucide-trash2').count(), 1)
  assert.match(await trash.getAttribute('class'), /text-danger/)
  await page.getByRole('checkbox', { name: 'Select Second clip', exact: true }).click()
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1000, 760))
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true)
  if (process.env.BRIDGECLIP_E2E_SHOTS) {
    fs.mkdirSync(process.env.BRIDGECLIP_E2E_SHOTS, { recursive: true })
    await page.screenshot({ path: path.join(process.env.BRIDGECLIP_E2E_SHOTS, 'delete-selected-clips.png'), animations: 'disabled' })
  }
  await trash.click()
  const confirmation = page.getByRole('alertdialog', { name: 'Delete these 2 clips?', exact: true })
  await confirmation.waitFor()
  await confirmation.getByText(/Your source video, transcript and editor edits will be kept/).waitFor()
  await confirmation.getByRole('button', { name: 'Cancel', exact: true }).press('Space')
  assert.ok(clips.slice(0, 3).every(clip => fs.existsSync(clip.s3_url)))
  assert.equal(JSON.parse(fs.readFileSync(manifest)).clips.length, 3)
  // A backend error leaves the selection and files available for a retry.
  fs.renameSync(manifest, `${manifest}.backup`)
  await trash.click()
  await page.getByRole('button', { name: 'Delete clips', exact: true }).click()
  await page.getByText('This completed run is no longer available in your Library.', { exact: true }).waitFor()
  assert.ok(clips.slice(0, 3).every(clip => fs.existsSync(clip.s3_url)))
  fs.renameSync(`${manifest}.backup`, manifest)
  await trash.click()
  await page.getByRole('button', { name: 'Delete clips', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Select First clip', exact: true }).waitFor({ state: 'detached' })
  await trash.waitFor({ state: 'detached' })
  assert.deepEqual(JSON.parse(fs.readFileSync(manifest)).clips.map(c => c.clip_index), [2])
  assert.equal(fs.existsSync(clips[0].s3_url), false)
  assert.equal(fs.existsSync(clips[1].s3_url), false)
  assert.ok(fs.existsSync(clips[2].s3_url))
  assert.ok(fs.existsSync(path.join(run, 'framing-source.mp4')))
  await page.getByRole('button', { name: 'Library', exact: true }).first().click()
  const runCard = page.locator('article').filter({ has: page.getByRole('button', { name: 'Open Delete selected test', exact: true }) })
  await runCard.getByText('1 clip', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Open Delete selected test', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Select all clips', exact: true }).click()
  await trash.click()
  await page.getByRole('button', { name: 'Delete clip', exact: true }).click()
  await page.getByText('No clips in this run', { exact: true }).waitFor()
  assert.equal(await trash.count(), 0)
  assert.equal(JSON.parse(fs.readFileSync(manifest)).total_clips, 0)
  assert.equal(JSON.parse(fs.readFileSync(manifest)).next_clip_index, 4)
  assert.ok(fs.existsSync(path.join(run, 'transcript.json')))
  await page.getByRole('button', { name: 'Library', exact: true }).first().click()
  await page.getByRole('button', { name: 'Open Delete selected test', exact: true }).click()
  await page.getByText('No clips in this run', { exact: true }).waitFor()
  assert.deepEqual(errors, [])
})
